Contact finalizado
4GeeksAcademy/TeamFM3 pull request #6
Opened 2024-07-26 23:07 UTC by MicaelaRojas

2024-07-26 23:22 UTC, mysticBel approved these changes

2024-07-26 23:48 UTC, ManuelLoaizaVasquez requested changes
LGTM. Only the white background is missing, @MicaelaRojas.

2024-07-26 23:57 UTC, Frcru requested changes
Agregar un div.row bg-light para tener todo el fondo de blanco
![image](https://github.com/user-attachments/assets/14ecec90-d404-4d01-8e0c-5c91e907cfcb)

2024-07-30 05:49 UTC, MicaelaRojas commented
Hola ya se agregó el background blanco 😄

2024-07-30 15:27 UTC, Frcru approved these changes
Well dONE!

2024-07-30 15:28 UTC, ManuelLoaizaV approved these changes
LGTM.

2024-07-30 15:28 UTC, merged